MvcProje/Models/ErrorViewModel.cs
namespace MvcProje.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcProje/Areas/Admin/Controllers/AbilityController.cs
using DataAccessLayer.Context;
using Microsoft.AspNetCore.Mvc;

namespace MvcProje.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class AbilityController : Controller
    {
        private readonly DataBaseUserContext db;

        public AbilityController(DataBaseUserContext context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var abilities = db.Abilities.ToList();

            return View(abilities);
        }
    }
}

MvcProje/Areas/Admin/Controllers/AdminController.cs
using DataAccessLayer.Context;
using Microsoft.AspNetCore.Mvc;
using Model.Entity;
using Model.ViewModels;

namespace MvcProje.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminController : Controller
    {
        private readonly DataBaseUserContext _db;

        public AdminController(DataBaseUserContext context)
        {
            _db = context;
        }

        public IActionResult Index()
        {
            var viewModel = new AuthenticationViewModel
            {
                Educations = _db.EducationDb.ToList(),
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult AddEducation()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddEducation(EducationDb education)
        {
            if (education != null)
            {
                _db.EducationDb.Add(education);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteEducation(int id)
        {
            var education = _db.EducationDb.Find(id);
            if (education != null)
            {
                _db.EducationDb.Remove(education);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditEducation(int id)
        {
            var education = _db.EducationDb.Find(id);
            return View(education);
        }

        [HttpPost]
        public IActionResult EditEducation(EducationDb education)
        {
            if (education != null)
            {
                _db.EducationDb.Update(education);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

MvcProje/Areas/Admin/Controllers/AuthenticationController.cs
using DataAccessLayer.Context;
using Microsoft.AspNetCore.Mvc;
using Model.Entity;
using Model.ViewModels;
using MvcProje.Areas.Admin.Filter;

namespace MvcProje.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthenticationController : Controller
    {
        private readonly DataBaseUserContext db;

        public AuthenticationController(DataBaseUserContext context)
        {
            db = context;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var viewModel = new AuthenticationViewModel
            {

                Abouts = db.AboutDb.ToList(),
                Experiences = db.ExperienceDb.ToList(),
                Educations = db.EducationDb.ToList(),
                Certificates = db.CertificateDb.ToList(),
                Contacts = db.ContactDb.ToList(),
            };

            return View(viewModel);
        }


    }

}

MvcProje/Areas/Admin/Controllers/CertificateController.cs
using DataAccessLayer.Context;
using Microsoft.AspNetCore.Mvc;
using Model.Entity;

namespace MvcProje.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CertificateController : Controller
    {
        private readonly DataBaseUserContext db;

        public CertificateController(DataBaseUserContext context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var certificates = db.CertificateDb.ToList();  
            return View(certificates);
        }
    }
}

MvcProje/Areas/Admin/Controllers/ContactController.cs
using DataAccessLayer.Context;
using Microsoft.AspNetCore.Mvc;
using Model.Entity;

namespace MvcProje.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactController : Controller 
    {
        private readonly DataBaseUserContext db;

        public ContactController(DataBaseUserContext context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var contacts = db.ContactDb.ToList(); 
            return View(contacts); 
        }
        
    }
}

MvcProje/Areas/Admin/Controllers/EducationController.cs
using DataAccessLayer.Context;
using Microsoft.AspNetCore.Mvc;
using Model.Entity;

namespace MvcProje.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EducationController : Controller
    {
        private readonly DataBaseUserContext db;

        public EducationController(DataBaseUserContext context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var educations = db.EducationDb.ToList();

            return View(educations);
        }
    }
}

MvcProje/Areas/Admin/Controllers/ExperienceController.cs
using DataAccessLayer.Context;
using Microsoft.AspNetCore.Mvc;
using Model.Entity;

namespace MvcProje.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ExperienceController : Controller
    {
        private readonly DataBaseUserContext db;

        public ExperienceController(DataBaseUserContext context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var experiences = db.ExperienceDb.ToList();
            return View(experiences);
        }

    }
}

MvcProje/Areas/Admin/Controllers/HobbyController.cs
using DataAccessLayer.Context;
using Microsoft.AspNetCore.Mvc;

namespace MvcProje.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HobbyController : Controller
    {
        private readonly DataBaseUserContext db;

        public HobbyController(DataBaseUserContext context)
        {
            db = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var Hobbies = db.Hobbies.ToList();

            return View(Hobbies);
        }
    }
}

MvcProje/Areas/Admin/Controllers/LogInController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DataAccessLayer.Context;
using ModelLayer.DTO;
using System.Text.Json;

namespace MvcProje.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LogInController : Controller
    {
        private readonly DataBaseUserContext _context;

        public LogInController(DataBaseUserContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(); // Login sayfasi
        }

        [HttpPost]
        public async Task<IActionResult> Index([FromForm] LogInDTO logInDTO)
        {


            if (ModelState.IsValid)
            {
                var adminUser = await _context.AdminDb
                    .FirstOrDefaultAsync(u => u.UserName == logInDTO.Username && u.Password == logInDTO.Password);

                if (adminUser != null)
                {
                    HttpContext.Session.SetString("AdminUsername", JsonSerializer.Serialize(adminUser));
                    return RedirectToAction("Index", "Admin", new { area = "Admin" });
                }

                ModelState.AddModelError(string.Empty, "Geçersiz kullanıcı adı veya şifre.");
            }

            return View(logInDTO); 
        }
    }
}

MvcProje/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcProje.Models;

namespace MvcProje.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcProje/Areas/Admin/Views/Ability/Index.cshtml
<div id="ability-section" class="resume-section-content">
    <h2 class="mb-5">Ability</h2>
    <div class="subheading mb-3">Programming Languages & Tools</div>
    <ul class="list-inline dev-icons">
        <div align="center">
            <a href="https://www.javascript.com/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/javascript-original.svg" alt="JavaScript" height="50" /></a>
            <a href="https://www.typescriptlang.org/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/typescript-original.svg" alt="TypeScript" height="50" /></a>
            <a href="https://www.php.net/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/php-original.svg" alt="PHP" height="50" /></a>
            <a href="https://www.linux.org/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/linux-original.svg" alt="Linux" height="50" /></a>
            <a href="https://www.python.org/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/python-original.svg" alt="Python" height="50" /></a>
            <a href="https://github.com/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/git-scm-icon.svg" alt="Git" height="50" /></a>
            <a href="https://www.gnu.org/software/bash/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/gnu_bash-icon.svg" alt="Bash" height="50" /></a>
            <a href="https://www.rabbitmq.com/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/rabbitmq-icon.svg" alt="RabbitMQ" height="50" /></a>
            <a href="https://dotnet.microsoft.com/download" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/dotnetcore.png" alt=".Net Core" height="50" /></a>
            <a href="https://en.wikipedia.org/wiki/HTML5" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/html5-original-wordmark.svg" alt="HTML5" height="50" /></a>
            <a href="https://dotnet.microsoft.com/download/dotnet-framework" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/dot-net-original-wordmark.svg" alt=".NET" height="50" /></a>
            <a href="https://www.mysql.com/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/mysql-original-wordmark.svg" alt="MySQL" height="50" /></a>
            <a href="https://unity.com/" target="_blank"><img style="margin: 10px" src="https://profilinator.rishav.dev/skills-assets/unity.png" alt="Unity" height="50" /></a>
        </div>
    </ul>

    <div class="subheading mb-3">Workflow</div>
    <ul class="fa-ul mb-0">
        <li>
            <span class="fa-li"><i class="fas fa-check"></i></span>
            Game development with Unity and C#
        </li>
        <li>
            <span class="fa-li"><i class="fas fa-check"></i></span>
            Building layered architecture in .NET projects
        </li>
        <li>
            <span class="fa-li"><i class="fas fa-check"></i></span>
            Database management and CRUD operations with Entity Framework
        </li>
        <li>
            <span class="fa-li"><i class="fas fa-check"></i></span>
            UI/UX design for mobile strategy games
        </li>
        <li>
            <span class="fa-li"><i class="fas fa-check"></i></span>
            Version control with Git and GitHub
        </li>
    </ul>
</div>

MvcProje/Areas/Admin/Views/Admin/Admin.cshtml
@using Model.ViewModels
@model AuthenticationViewModel





<!DOCTYPE html>
<html>
<head>
    <title>W3.CSS Template</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/5/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <style>
        body,h1 {font-family: "Raleway", sans-serif}
        body, html {height: 100%}
        .bgimg {
          background-image: url('/w3images/forestbridge.jpg');
          min-height: 100%;
          background-position: center;
          background-size: cover;
        }
    </style>
</head>
<body>

    <div class="bgimg w3-display-container w3-animate-opacity w3-text-white">
        <div class="w3-display-topleft w3-padding-large w3-xlarge">
            Logo
        </div>
        <div class="w3-display-middle">
            <h1 class="w3-jumbo w3-animate-top">COMING SOON</h1>
            <hr class="w3-border-grey" style="margin:auto;width:40%">
            <p class="w3-large w3-center">35 days left</p>
        </div>
        <div class="w3-display-bottomleft w3-padding-large">
            Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a>
        </div>
    </div>

</body>
</html>

MvcProje/Areas/Admin/Views/Admin/Index.cshtml
@model Model.ViewModels.AuthenticationViewModel


<div class="container py-4">
    <div class="card shadow-sm rounded-4">
        <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center rounded-top-4">
            <h4 class="mb-0">📚 Education List</h4>
            <a href="/Admin/Admin/AddEducation" class="btn btn-light fw-bold shadow-sm">+ Add New Education</a>
        </div>
        <div class="card-body p-0">
            <table class="table table-hover table-bordered mb-0">
                <thead class="table-light">
                    <tr class="text-center align-middle">
                        <th>ID</th>
                        <th>Title</th>
                        <th>Subtitle</th>
                        <th>Subtitle 2</th>
                        <th>GPA</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model?.Educations != null)
                    {
                        foreach (var item in Model.Educations)
                        {
                            <tr class="text-center align-middle">
                                <td>@item.Id</td>
                                <td>@item.Title</td>
                                <td>@item.Subtitle</td>
                                <td>@item.Subtitle2</td>
                                <td>@item.Gno</td>
                                <td>@item.Date</td>
                                <td>
                                    <a href="/Admin/Admin/EditEducation/@item.Id" class="btn btn-warning btn-sm">Edit</a>
                                    <a href="/Admin/Admin/DeleteEducation/@item.Id" class="btn btn-danger btn-sm">Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

MvcProje/Areas/Admin/Views/Authentication/Index.cshtml
@using Model.ViewModels
@model AuthenticationViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Resume - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/startbootstrap-resume-gh-pages/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="d-block d-lg-none">Alperen Can</span>
            <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="/startbootstrap-resume-gh-pages/assets/img/Me.jpg" alt="" /></span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#experience">Experience</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#education">Education</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#ability">Ability</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#hobby">Hobby</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#certificate">Certificate</a></li>
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
            </ul>
        </div>
    </nav>
    <!-- Page Content-->
    <div class="container-fluid p-0">
        <!-- About-->
        @foreach (var x in Model?.Abouts)
        {
            <section class="resume-section" id="about">
                <div class="resume-section-content">
                    <h1 class="mb-0">
                        @x.Name
                        <span class="text-primary">@x.Surname</span>
                    </h1>
                    <div class="subheading mb-5">
                        @x.Address
                        <a href="mailto:name@email.com">@x.Mail</a>
                    </div>
                    <p class="lead mb-5">@x.Description</p>
                    <div class="social-icons">
                        <a class="social-icon" href="https://www.linkedin.com/in/alperencan1/"><i class="fab fa-linkedin-in"></i></a>
                        <a class="social-icon" href="https://github.com/alperencaan"><i class="fab fa-github"></i></a>
                        <a class="social-icon" href="https://x.com/teestamentt16"><i class="fab fa-twitter"></i></a>
                    </div>
                </div>
            </section>
        }
        <hr class="m-0" />
        <!-- experience-->
        <section class="resume-section" id="experience">
            @Html.Partial("~/Areas/Admin/Views/Experience/Index.cshtml")
        </section>

        <hr class="m-0" />
        <!-- Education-->
        <section class="resume-section" id="education">
            @Html.Partial("~/Areas/Admin/Views/Education/Education.cshtml")
        </section>
        <hr class="m-0" />
        <!-- Skills-->
        <section class="resume-section" id="ability">
            @Html.Partial("/Areas/Admin/Views/Ability/Index.cshtml")
        </section>
        <hr class="m-0" />
        <!-- Interests-->
        <section class="resume-section" id="hobby">
            @Html.Partial("/Areas/Admin/Views/Hobby/Hobby.cshtml")
        </section>
        <hr class="m-0" />
        <!-- Certificates-->
        <section class="resume-section" id="certificate">
            @Html.Partial("/Areas/Admin/Views/Certificate/Certificate.cshtml")
        </section>
        <hr class="m-0" />
        <!-- Contact-->
        <section class="resume-section" id="contact">
            @Html.Partial("/Areas/Admin/Views/Contact/Contact.cshtml")
        </section>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Core theme JS-->
    <script src="/startbootstrap-resume-gh-pages/"></script>
</body>
</html>

MvcProje/Areas/Admin/Views/Certificate/Certificate.cshtml
@using Model.ViewModels
@model AuthenticationViewModel




<section class="resume-section" id="Certificate">
    <div class="resume-section-content">
        <h2 class="mb-5">Certifications</h2>
        <ul class="fa-ul mb-0">
            @foreach (var certificate in Model.Certificates)
            {
                <li>
                    <span class="fa-li"><i class=""></i></span>
                    @certificate.Certificatee
                </li>
            }
        </ul>
    </div>
</section>

MvcProje/Areas/Admin/Views/Contact/Contact.cshtml
@using Model.ViewModels
@model AuthenticationViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Page</title>
    <!-- Bootstrap & FontAwesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <style>
        body {
            background: #f8f9fa;
            font-family: 'Lato', sans-serif;
        }

        .contact-header h2 {
            font-size: 2.5rem;
            font-weight: 700;
        }

        .contact-header p {
            color: #6c757d;
        }

        .contact-card {
            border: none;
            border-radius: 1rem;
            box-shadow: 0 2px 12px rgba(0,0,0,0.07);
            margin-bottom: 1.5rem;
        }

            .contact-card .card-body {
                padding: 1.5rem 2rem;
            }

        .contact-date {
            font-size: 0.95rem;
            color: #888;
            text-align: right;
        }

        .form-control:focus {
            box-shadow: 0 0 0 0.2rem rgba(0,123,255,.15);
        }

        .btn-send {
            font-weight: bold;
            letter-spacing: 1px;
            border-radius: 2rem;
            padding: 0.5rem 2rem;
        }
    </style>
</head>
<body>
    <section class="container py-5" id="contact">
        <div class="contact-header text-center mb-5">
            <h2><i class="fas fa-envelope-open-text text-primary"></i> Contact</h2>
            <p><i>contact me</i></p>
        </div>

        <!-- Contact Messages -->
        @foreach (var contact in Model.Contacts)
        {
            <div class="card contact-card">
                <div class="card-body d-flex flex-column flex-md-row justify-content-between align-items-md-center">
                    <div>
                        <h5 class="mb-1"><i class="fas fa-user-circle text-secondary"></i> @contact.UserName</h5>
                        <div><strong><i class="fas fa-envelope"></i> E-Mail:</strong> @contact.Mail</div>
                        <div><strong><i class="fas fa-tag"></i> Subject:</strong> @contact.Subject</div>
                        <div><strong><i class="fas fa-comment-dots"></i> Message:</strong> @contact.Message</div>
                    </div>
                    <div class="contact-date mt-3 mt-md-0">
                        <i class="fas fa-calendar-alt"></i> @contact.Date.ToString("dd.MM.yyyy HH:mm")
                    </div>
                </div>
            </div>
        }

        <!-- Contact Form -->
        <div class="card contact-card mt-4">
            <div class="card-body">
                <form action="@Url.Action("SubmitContact", "Home")" method="post">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input class="form-control" type="text" placeholder="Name" required name="UserName" />
                        </div>
                        <div class="form-group col-md-6">
                            <input class="form-control" type="email" placeholder="Email" required name="Mail" />
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" placeholder="Subject" required name="Subject" />
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" placeholder="Message" required name="Message" rows="5"></textarea>
                    </div>
                    <div class="text-right">
                        <button class="btn btn-primary btn-send" type="submit">
                            <i class="fas fa-paper-plane"></i> SEND
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</body>
</html>

MvcProje/Areas/Admin/Views/LogIn/Index.cshtml
@model ModelLayer.DTO.LogInDTO

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login Page</title>
    <style>
        :root {
            --main-orange: #ff7300;
            --main-orange-dark: #e65c00;
            --main-orange-light: #ffb380;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Exo', sans-serif;
            background: #1d1f2e;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            overflow: hidden;
            position: relative;
        }

        .background-image {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-image: url('https://images.unsplash.com/photo-1506748686217-3f055d496010');
            background-size: cover;
            background-position: center;
            filter: blur(8px);
            z-index: -1;
        }

        .container {
            width: 400px;
            background-color: rgba(0, 0, 0, 0.7);
            border-radius: 10px;
            padding: 40px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
        }

        .header {
            text-align: center;
            font-size: 28px;
            margin-bottom: 30px;
            color: var(--main-orange-light);
            font-weight: 300;
        }

            .header span {
                color: var(--main-orange);
                font-weight: 700;
            }

        .login-form input[type="text"],
        .login-form input[type="password"] {
            width: 100%;
            padding: 15px;
            margin: 10px 0;
            background: transparent;
            border: 2px solid var(--main-orange);
            border-radius: 5px;
            color: #fff;
            font-size: 16px;
            outline: none;
            transition: border 0.3s;
        }

            .login-form input[type="text"]:focus,
            .login-form input[type="password"]:focus {
                border-color: var(--main-orange-light);
            }

        .login-form input[type="submit"] {
            width: 100%;
            padding: 15px;
            background: var(--main-orange);
            border: none;
            border-radius: 5px;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
            transition: background 0.3s;
        }

            .login-form input[type="submit"]:hover {
                background: var(--main-orange-dark);
            }

        .login-form a {
            display: block;
            text-align: center;
            margin-top: 15px;
            color: #fff;
            text-decoration: none;
            font-size: 14px;
            transition: color 0.3s;
        }

            .login-form a:hover {
                color: var(--main-orange-light);
            }
    </style>
</head>
<body>
    <div class="background-image"></div>
    <div class="container">
        <div class="header">
            
            ADMIN<span>LOGIN</span>
        </div>
        <div class="login-form">
            <form asp-action="Index" asp-controller="LogIn" asp-area="Admin" method="post">
                <input asp-for="Username" name="Username" placeholder="Username" type="text" required />
                <input asp-for="Password" name="Password" type="password" placeholder="Password" required />
                <input type="submit" value="Login" />
            </form>
            <a href="#">Forgot Password?</a>
        </div>
    </div>
</body>
</html>

MvcProje/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<section id="about">
    <h2>@Model.Name @Model.Surname</h2>
    <p>@Model.Description</p>
    <p>@Model.Address - @Model.Phone - @Model.Mail</p>
    <img src="@Model.Image" alt="Hakkında Resmi" />
</section>